apiVersion: solution.symphony/v1
kind: Solution
metadata:
  name: alert-engine-v-1
spec:
  rootResource: alert-engine
  metadata:
    deployment.replicas: "#1"
    service.ports: "[{\"name\":\"metrics\",\"port\":8087}]"
    service.type: "ClusterIP"
  components:
  - name: alert-engine
    type: container
    properties:
      container.image: "alert-engine:latest"
      container.imagePullPolicy: "IfNotPresent"
      container.ports: "[{\"containerPort\":8087,\"protocol\":\"TCP\"}]"
      container.resources: "{\"requests\":{\"cpu\":\"100m\",\"memory\":\"128Mi\"}}"
      metadata.annotations: "{\"prometheus.io/scrape\":\"true\",\"prometheus.io/port\":\"8087\"}"
