apiVersion: solution.symphony/v1
kind: Solution
metadata:
  name: iot-sim-v-1
spec:
  rootResource: iot-sim
  metadata:
    deployment.replicas: "#3"
    service.ports: "[{\"name\":\"metrics\",\"port\":8085}]"
    service.type: "ClusterIP"
  components:
    - name: iot-sim
      type: container
      properties:
        container.image: "iot-sim:latest"
        container.imagePullPolicy: "IfNotPresent"
        container.ports: "[{\"containerPort\":8085,\"protocol\":\"TCP\"}]"
        container.resources: "{\"requests\":{\"cpu\":\"50m\",\"memory\":\"64Mi\"}}"
        metadata.annotations: "{\"prometheus.io/scrape\":\"true\",\"prometheus.io/port\":\"8085\"}"
